/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.22 from the
 * contents of GenerateSSLCerts.xs. Do not edit this file, edit GenerateSSLCerts.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "GenerateSSLCerts.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#include "ppport.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <openssl/x509.h>
#include <openssl/x509v3.h>
#include <openssl/err.h>
#include <openssl/pem.h>
#include <openssl/evp.h>

#define PACKAGE_NAME "GenerateSSLCerts"
#define RSA_KEY_SIZE (1024) 
#define ENTRIES 6 

void fatal_error(const char *file, int line, const char *msg) {
        fprintf(stderr, "**FATAL** %s:%i %s\n", file, line, msg); 
        ERR_print_errors_fp(stderr); 
        exit(-1);
}

#define fatal(msg) fatal_error(__FILE__, __LINE__, msg) 


struct entry 
{ 
    char *key; 
    char *value; 
}; 

struct entry entries[ENTRIES] = 
{ 
    { "countryName", "NL" }, 
    { "stateOrProvinceName", "NH" }, 
    { "localityName", "Amsterdam" }, 
    { "organizationName", "granite" }, 
    { "organizationalUnitName", "Development" }, 
    { "commonName", "granite" }, 
}; 


#line 54 "GenerateSSLCerts.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 196 "GenerateSSLCerts.c"

XS_EUPXS(XS_GenerateSSLCerts_gen_key_n_cert); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_GenerateSSLCerts_gen_key_n_cert)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "key_file, cert_file");
    {
#line 50 "GenerateSSLCerts.xs"
        int i;
        RSA *rsakey; 
        X509_REQ *req; 
        X509_NAME *subj; 
        EVP_PKEY *pkey; 
        EVP_MD *digest; 
        FILE *fp;   
#line 213 "GenerateSSLCerts.c"
	int	RETVAL;
	dXSTARG;
	char*	key_file = (char *)SvPV_nolen(ST(0))
;
	char*	cert_file = (char *)SvPV_nolen(ST(1))
;
#line 59 "GenerateSSLCerts.xs"
        OpenSSL_add_all_algorithms(); 
        ERR_load_crypto_strings(); 

        rsakey = RSA_generate_key(RSA_KEY_SIZE, RSA_F4, NULL, NULL); 

        if (!(pkey = EVP_PKEY_new())) 
            fatal("Could not create EVP object"); 

        if (!(EVP_PKEY_set1_RSA(pkey, rsakey))) 
            fatal("Could not assign RSA key to EVP object"); 

        if (!(req = X509_REQ_new())) 
            fatal("Failed to create X509_REQ object"); 
        X509_REQ_set_pubkey(req, pkey); 

        if (!(subj = X509_NAME_new())) 
            fatal("Failed to create X509_NAME object"); 

        for (i = 0; i < ENTRIES; i++) 
        { 
            int nid;
            X509_NAME_ENTRY *ent; 

            if ((nid = OBJ_txt2nid(entries[i].key)) == NID_undef) 
            { 
                fprintf(stderr, "Error finding NID for %s\n", entries[i].key); 
                fatal("Error on lookup"); 
            } 
            if (!(ent = X509_NAME_ENTRY_create_by_NID(NULL, nid, MBSTRING_ASC, 
                entries[i].value, - 1))) 
                fatal("Error creating Name entry from NID"); 

            if (X509_NAME_add_entry(subj, ent, -1, 0) != 1) 
                fatal("Error adding entry to Name"); 
        } 
        if (X509_REQ_set_subject_name(req, subj) != 1) 
            fatal("Error adding subject to request"); 

        digest = (EVP_MD *)EVP_sha1(); 

        if (!(X509_REQ_sign(req, pkey, digest))) 
            fatal("Error signing request"); 

        if (!(fp = fopen(cert_file, "w"))) 
            fatal("Error writing to request file"); 
        if (PEM_write_X509_REQ(fp, req) != 1) 
            fatal("Error while writing request"); 
        fclose(fp); 

        if (!(fp = fopen(key_file, "w"))) 
            fatal("Error writing to private key file"); 
        if (PEM_write_PrivateKey(fp, pkey, NULL, NULL, 0, 0, NULL) != 1) 
            fatal("Error while writing private key"); 
        fclose(fp); 

        free(cert_file);
        free(key_file);

        EVP_PKEY_free(pkey); 
        X509_REQ_free(req);

    RETVAL = 0;
#line 283 "GenerateSSLCerts.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_GenerateSSLCerts); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_GenerateSSLCerts)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        newXS("GenerateSSLCerts::gen_key_n_cert", XS_GenerateSSLCerts_gen_key_n_cert, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

